version: '3.8'
services:
  configserver:
    container_name: configserver
    image: sagen0211/config-server:latest
    ports:
    - "8008:8008"
    networks:
    - sagen-network
  eurekaserver:
    container_name: eurekaserver
    image: sagen0211/eureka-server:latest
    ports:
    - "9009:9009"
    networks:
    - sagen-network
    depends_on:
    - configserver
    deploy:
      restart_policy:
        condition: on-failure
        delay: 30s
        max_attempts: 3
        window: 120s
    environment:
      SPRING_PROFILES_ACTIVE: default
      SPRING_CONFIG_IMPORT: configserver:http://configserver:8008/
  accounts:
    container_name: accounts-service
    image: sagen0211/accounts:latest
    build: .
    ports:
    - "8001:8001"
    links:
    - db
    depends_on:
    - configserver
    - eurekaserver
    - db
    deploy:
      restart_policy:
        condition: on-failure
        delay: 50s
        max_attempts: 3
        window: 120s
    environment:
      SPRING_PROFILES_ACTIVE: default
      SPRING_CONFIG_IMPORT: configserver:http://configserver:8008/
      EUREKA_CLIENT_SERVICE_URL_DEFAULT_ZONE: http://eurekaserver:9009/eureka/
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/bank_services
  db:
    container_name: postgresql
    image: postgres
    ports:
    - "5432:5432"
    environment:
    - POSTGRES_PASSWORD=docker@2020
    - POSTGRES_USER=postgres
    - POSTGRES_DB=bank_services
  loans:
    container_name: loans-service
    image: sagen0211/loans:latest
    ports:
    - "8002:8002"
    networks:
    - sagen-network
    depends_on:
    - configserver
    - eurekaserver
    deploy:
      restart_policy:
        condition: on-failure
        delay: 50s
        max_attempts: 3
        window: 120s
    environment:
      SPRING_PROFILES_ACTIVE: default
      SPRING_CONFIG_IMPORT: configserver:http://configserver:8008/
      EUREKA_CLIENT_SERVICE_URL_DEFAULT_ZONE: http://eurekaserver:9009/eureka/
  cards:
    container_name: cards-service
    image: sagen0211/cards:latest
    ports:
    - "8003:8003"
    networks:
    - sagen-network
    depends_on:
    - configserver
    - eurekaserver
    deploy:
      restart_policy:
        condition: on-failure
        delay: 50s
        max_attempts: 3
        window: 120s
    environment:
      SPRING_PROFILES_ACTIVE: default
      SPRING_CONFIG_IMPORT: configserver:http://configserver:8008/
      EUREKA_CLIENT_SERVICE_URL_DEFAULT_ZONE: http://eurekaserver:9009/eureka/
networks:
  sagen-network: 